blackbaud/skyux-builder

- config/protractor/protractor.conf.js
Update the e2e config to use the SSL version of the site but allow for certificate errors in Chrome
> Update the e2e config to use the SSL version of the site but allow for certificate errors in Chrome.

- cli/e2e.js
- test/cli-e2e.spec.js
Fixes a bug @Blackbaud-JonathanBell pointed out, where e2e command doesn't "fail the build."
> Passing protractor exit code through.  Tests

- config/webpack/serve.webpack.config.js
- test/config-webpack-serve.spec.js
Currently, `skyux serve` will open the host url but include the app base twice.  This is caused due to updates to `host-utils`.
I first updated my test to fail in it's current state (making what url I test is opened more strict).  Then fixed the bug and have the test pass.
> Wrote failing test.  Fixed bug.  Test passes for opening host url with base twice

- config/webpack/test.webpack.config.js
Karma currently only detects and finds `.spec` files inside of `src/app`.  This change would allow Karma to look for and detect the all test specific files inside the `src` folder instead, allowing user created modules to follow the best practice pattern and test their modules to skyux standards.
> find .spec files from src.

- config/webpack/test.webpack.config.js
Reverting 243497925a786dfbbd5cc99f0c16ac3d6b6f3b22.  May look at making component creation more first-class in the future.
> Reverted to src/app for tests/imports

- config/webpack/common.webpack.config.js
- config/webpack/test.webpack.config.js
- Removed `postload` from webpack loaders, until we have a use-case for it.
- Fixes [issue 642](https://github.com/blackbaud/skyux2/issues/642).
> Fixed TypeScript in sourcemaps

- config/webpack/test.webpack.config.js
Addresses [issue #527](https://github.com/blackbaud/skyux2/issues/527)
- I created another pull request for the [SKY UX Template](https://github.com/blackbaud/skyux-template/pull/23) to fix some linting errors, otherwise new SPA's will fail on build.
> Lint errors abort the build

- src/app/app.component.ts
Without this, even though we removed the BBOmnibarConfig, we'd still have to update both to pass through any new properties.
> Passing through omnibar config

- package.json
- runtime/config.ts
- src/app/app.component.ts
- Added support for specifying local navigation in skyuxconfig.json
- Refactored `publicRoutes` property to `routes` with `public` and `referenced` properties in preparation for publishing to the nav service
> Local omnibar nav and routes rename

- config/sky-pages/sky-pages.config.js
- test/config-sky-pages.spec.js
- test/host-utils.spec.js
Currently if editing the skyuxconfig.json file in Visual Studio, it addes a Byte Order Mark to the file, which causes the json parse to explode.  
https://github.com/nodejs/node-v0.x-archive/issues/1918#issuecomment-2480359
This is a work around as readFileSync doesn't strip out BOM by default. 
Related to:
https://github.com/blackbaud/skyux2/issues/700
> added a replace string to remove BOM from json file before parse

- loader/sky-processor/index.js
- test/loader-processor.spec.js
This feature provides the `skyPagesConfig` object to plugin `preload` and `postload` hooks.
```
module.exports = {
preload: (content, resourcePath, skyAppConfig) => {
return content;
}
};
```
> Add config to plugin callbacks

- cli/test.js
- config/karma/dev.karma.conf.js
- config/karma/shared.karma.conf.js
- config/webpack/test.webpack.config.js
- index.js
- test/cli-test.spec.js
- test/config-webpack-test.spec.js
**How to test:**
- Type `skyux watch --no-coverage` <-- instrument loader will not mangle the source files
Addresses [issue #643](https://github.com/blackbaud/skyux2/issues/643)
> Added --no-coverage flag to `skyux watch`

- cli/e2e.js
- test/cli-e2e.spec.js
Addresses [issue #721](https://github.com/blackbaud/skyux2/issues/721).
Aside from running e2e, this branch tests for several failures, including `http-server`, `selenium`, `webdriver-manager`, and `protractor`.
- To test, purposefully break one of your e2e tests (skyux-template repo has a sample test)
- Run `skyux e2e && echo "hello"` <-- "hello" should never be printed to the console.
> e2e tests fail build

- config/webpack/serve.webpack.config.js
- test/config-webpack-serve.spec.js
Tested in OSX and Windows against `chrome`, `firefox`, `safari`, `iexplore`, and `edge`.  
A few notes:
- `edge` has to be a hard-coded use-case since they only expose a protocol `microsoft-edge:` instead of an executable.
- This only updates the `skyux serve` command.  Support could also be added for the `skyux test`, `skyux watch`, and `skyux e2e` commands.
Fixes https://github.com/blackbaud/skyux2/issues/402
> Allowing browser flag in serve

- config/webpack/common.webpack.config.js
- config/webpack/test.webpack.config.js
- plugin/process-exit-code/index.js
- test/config-webpack-common.spec.js
Fixes https://github.com/blackbaud/skyux2/issues/755
> Modernizing ProcessExitCode plugin

- e2e/shared/common.js
- e2e/shared/tests.js
- e2e/skyux-build-aot.e2e-spec.js
- e2e/skyux-build-jit.e2e-spec.js
- lib/sky-pages-module-generator.js
- lib/sky-pages-route-generator.js
- test/sky-pages-route-generator.spec.js
Adds support for canActivate/canDeactivate route guards as requested in blackbaud/skyux2#423.
I want to look at refactoring the way route generation works to use childRoutes and all for canActivateChild as well but this is a solid first step to unblock some consumers.
> Add support for route guards

- lib/sky-pages-route-generator.js
- test/sky-pages-route-generator.spec.js
Fixes the bathing to use the runtime alias. Also flips `\` to `/` for module loading on windows. Confirmed fix on Win7 and OSX.
> Stop resolving, fix windows guard paths

- e2e/shared/common.js
- e2e/shared/tests.js
- e2e/skyux-build-aot.e2e-spec.js
- e2e/skyux-build-jit.e2e-spec.js
- lib/sky-pages-route-generator.js
- test/sky-pages-route-generator.spec.js
PR implements child routing based on the design @Blackbaud-PaulCrowder and I discussed.
A directory prefixed with # such as src/app/about/#child would create a child-route underneath /about which can be affected by canActivateChild guards as well as used by controls that implement router-outlet in their template such as the future tab control (or currently microedge contrib tab control).
A directory without the prefix but underneath a child route such as src/app/about/#child/top-level will break out and become a top level route that cannot be affected by canActivateChild guards and will not participate in router-outlet.
All other routes will continue to be top-level. Routes continue to only be created if an index.html is provided.
Additionally now that we have child routing, I've also …
> Child route support, root guard support

- runtime/params.spec.ts
- runtime/params.ts
- src/app/app.component.spec.ts
- src/app/app.component.ts
- Fixed typo in OmnibarConfigMap (`svid` -> `svcid`)
- Allowing query string params to be case insensitive (uses case specified in `skyuxconfig.json` when setting)
> Param functionality

- lib/sky-pages-route-generator.js
- test/sky-pages-route-generator.spec.js
Due to updated AoT rules, `config` needs to be marked as public in order to be accessible in an auto-generated component's template (`index.html`).
@blackbaud-johnly, we'll also need to update https://developer.blackbaud.com/skyux2/learn/reference/configuration/apply-appsettings to show it being `public`.
> Wrote failing test.  Then made config property public for template

- config/webpack/build-aot.webpack.config.js
- test/config-webpack-build-aot.spec.js
Since the preloader is executed on the file system during an AoT build, the loader is run twice: once, during the [webpack build](https://github.com/blackbaud/skyux-builder/blob/master/config/webpack/common.webpack.config.js#L95), and second, in the [`stageAot`](https://github.com/blackbaud/skyux-builder/blob/master/cli/build.js#L108) method.
This duplicate behavior causes plugins to process files twice during AoT, causing things like this (the double-escaped brackets):
https://developer.blackbaud.com/skyux2/learn/reference/configuration
> Removed preloader from AoT Webpack config

- config/protractor/protractor-dev.conf.js
- runtime/style-loader.ts
- utils/sky-style-loader.js
Since the font families have changed in SKY UX rc.7, the style loader doesn't resolve in time and causes Jasmine tests to timeout.
> Updated font families in style loader

- package.json
`@ngtools/webpack@1.3.1` created a transient dependecy for `enhanced-resolve`, which prevents `skyux build` from completing.
More information:
https://github.com/angular/angular-cli/issues/7113
> Fix: Added specific version of enhanced-resolve

- config/karma/dev-runtime.karma.conf.js
- runtime/i18n/resources.pipe.spec.ts
- runtime/i18n/resources.pipe.ts
https://github.com/blackbaud/skyux2/issues/933
> Mark change detector for check after a resource string is loaded asynchronously

- cli/utils/ts-linter.js
- test/cli-utils-ts-linter.spec.js
- TSLint was only logging `stderr` and ignoring `stdout`. However, the status code would return as non-zero because the `stdout` reported linting errors in node_modules.
- To avoid this, I'm excluding node_modules for the TSLint CLI, as well as parsing the entire child process output for messages.
> Fixed TSLint checking node_modules

- cli/serve.js
- test/cli-serve.spec.js
Fixes https://github.com/blackbaud/skyux2/issues/717
> Specifying host when listening for WebpackDevServer

- runtime/testing/browser/matchers.ts
Old:
New:
As a developer, I'd like to view what the actual value returned on failing errors so that I can more quickly see the differences between expected and actual.
> Change toHaveText to have a more verbose error message

- cli/e2e.js
Fixes https://github.com/blackbaud/skyux2/issues/1009
Since we, currently, only use Chrome in our selenium tests, we can add this flag to disable pulling down the gecko driver.  If we ever add Firefox to our test suite, we'll need to make sure to disable this.
> Disabled gecko for webdriver-manger update

- package.json
@Blackbaud-BobbyEarl having the `@blackbaud/help-client`  as a dependency of builder at the `1.0.1` version is causing an error preventing the widget from loading.  The `BBHelp` was renamed to `BBHelpClient` in `1.0.2` (probably should have been called `2.0.0`).
> removed unneeded dependency

- runtime/index.ts
Addresses https://github.com/blackbaud/skyux2/issues/1122
> Exporting assets service

- cli/build.js
- config/protractor/protractor-dev.conf.js
- config/sky-pages/sky-pages.config.js
- e2e/shared/common.js
- package.json
- test/cli-utils-browser.spec.js
- test/config-sky-pages.spec.js
- test/utils-merge-utils.spec.js
- utils/merge.js
- utils/runtime-test-utils.js
Fixes https://github.com/blackbaud/skyux2/issues/1148
> [HOLD] Using lodash.merge for all merges (except webpack).

- .travis.yml
This was a quick experiment in making the build slightly quicker.  It moves the coverage and e2e steps into separate "environments."  While not a huge impact, it does shave a couple minutes off the total "real" time needed.
> Using a build matrix to split coverage/e2e

- src/app/app.component.scss
CSS override for help invoker not working with the `/deep/` modifier.  removed it to enable the bug fix for hiding the invoker with full page modals to function properly.
> removed /deep/ for page level classes

- package.json
Other PRs are more likely to fail in Appveyor until this PR is merged in.
> Disabling pulling down gecko for internal protractor tests

- config/webpack/test.webpack.config.js
- test/config-webpack-test.spec.js
Fixes https://github.com/blackbaud/skyux2/issues/1222
> Wrapped the first and last parts with path separators so that only distinct parts are matched

- src/app/app.component.spec.ts
- src/app/app.component.ts
Omnibar uses `setInterval()` to detect user activity, but running this
inside Angular causes change detection to run every cycle.  Loading
omnibar outside Angular avoids this.
> Load omnibar outside Angular

- src/app/app.component.spec.ts
- src/app/app.component.ts
Fixes https://github.com/blackbaud/skyux2/issues/1286
> Fixed a bug preventing navigation via omnibar due to loading outside Angular

- plugin/output-keep-alive/index.js
- test/plugin-output-keep-alive.spec.js
@Blackbaud-BobbyEarl: I believe `stdout` is causing the JavaScript heap issue because it's getting called several times in three different locations (and apparently, because stdout is asynchronous, it has a known problem of causing out-of-memory problems, especially in "blocking" contexts, such as loops). https://stackoverflow.com/questions/38085746/why-does-writing-to-stdout-in-a-hot-loop-cause-an-out-of-memory-shutdown
I reduced the number of calls to a single lifecycle hook, and the heap problem stopped (I'm also increasing the amount of memory available for the `skyux build` command, here: https://github.com/blackbaud/skyux2/pull/1285/files#diff-be484b29d7890da24734b568487a490bR8).
> Reduced number of console logs for output keep alive

- cli/build.js
- config/webpack/build-aot.webpack.config.js
- config/webpack/common.webpack.config.js
- lib/sky-pages-module-generator.js
Turns out the build was pulling from node_modules, which is why it was so slow. There are a few other updates I'd like to make, but this should do for now.
This UX pull request is referencing this branch:
https://github.com/blackbaud/skyux2/pull/1294
> Faster build

- src/app/app.component.spec.ts
- src/app/app.component.ts
Accessing the `SKYUX_HOST` if it exists from HOST, and grabbing the `acceptLanguage` so the Help config will be updated to use the locale.
> Feature localize help

- config/karma/shared.karma.conf.js
- runtime/config.ts
- test/config-karma-shared.spec.js
Addresses https://github.com/blackbaud/skyux2/issues/513
> Added codeCoverageThreshold property and tests

- package.json
This is just a good move in general.  Specifically doing it now as I attempt to evaluate stackblitz.com, which requires dependencies to be published to npm.
> Changed dep from GitHub to NPM

- lib/sky-pages-module-generator.js
- runtime/directives/index.ts
- runtime/directives/sky-app-link-external.directive.spec.ts
- runtime/directives/sky-app-link-external.directive.ts
We need to navigate to an other SPA but maintain service and environment context. So, we need to sidestep the Angular router but still get the same behavior as `skyAppLink` to maintain the runtime context for the SPA.
- First commit for review on overall approach before writing tests
> Contribute `skyAppLinkExternal`

- cli/serve.js
- config/webpack/serve.webpack.config.js
- src/main-internal.ts
- test/cli-serve.spec.js
Investigating solving https://github.com/blackbaud/skyux2/issues/406.  To test, install this branch and run `skyux serve --hmr` . We could also evaluate this being the default behavior.  Whichever is decided, a docs change would be necessary.
> Enable hmr

- config/karma/shared.karma.conf.js
- config/protractor/protractor.conf.js
- test/config-karma-shared.spec.js
- test/config-protractor.spec.js
I foolishly missed updating the Karma and Protractor configurations to honor the newly created `@blackbaud/skyux-logger`.
> Using logger.logColor for Karma and Protractor

- cli/e2e.js
- cli/test.js
- test/cli-e2e.spec.js
- test/cli-test.spec.js
This should shave off a couple minutes of builds, mainly for Stache sites that contain to unit tests.
> Added test + logic to shortcircuit test command

- runtime/testing/browser/test-utility-dom-event-options.ts
- runtime/testing/browser/test-utility.ts
**Allows firing of keyboard events.**
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/KeyboardEvent
```
SkyAppTestUtility.fireDomEvent(autocompleteElement, 'keydown', {
bubbles: true,
keyboardEventInit: { key: 'Enter' }
});
```
FYI: I replaced all instances of `TestUtility` from SKY UX's spec files with success:
https://github.com/blackbaud/skyux2/pull/1598
> Added 'keyboardEventInit' to test utility

- runtime/testing/browser/matchers.ts
This adjustment was made for SKY UX, but since we're removing that in favor of Builder's matchers, it would be good to bring this over too:
https://github.com/blackbaud/skyux2/pull/1422
> Using textContent instead of innerText for matcher

- runtime/directives/sky-app-link-external.directive.spec.ts
- runtime/directives/sky-app-link.directive.spec.ts
- runtime/directives/sky-app-link.directive.ts
https://github.com/blackbaud/skyux2/issues/1603
> Fixed query param issue skyAppLink

- runtime/i18n/host-locale-provider.ts
- runtime/index.ts
This will allow folks to import the runtime module via the barrel:
`import { SkyAppRuntimeModule } from '@blackbaud/skyux-builder/runtime'`
> Added module to runtime index

- cli/build.js
- runtime/directives/sky-app-link.directive.spec.ts
- runtime/directives/sky-app-link.directive.ts
- runtime/params.spec.ts
- runtime/params.ts
Addressing https://github.com/blackbaud/skyux2/issues/1650
> Update skyAppLink to use optional excludeDefaults to getAll.

- cli/utils/stage-library-ts.js
- package.json
Addresses: https://github.com/blackbaud/skyux2/issues/1740
> Libraries > Support tilde imports for SCSS files

- config/karma/shared.karma.conf.js
Adding `lcov` to the outputs for Istanbul so we can make use of some code coverage tooling in VSCode.
> Added lcov to output types for istanbul

- runtime/auth-http.spec.ts
- runtime/bootstrapper.spec.ts
- runtime/config-params.ts
- runtime/params.spec.ts
- runtime/params.ts
See:
https://github.com/blackbaud/skyux2/projects/9#card-10723415
https://github.com/blackbaud/skyux2/projects/9#card-10723731
> RC > Config params as an object; always decode URL params

- runtime/auth-http.spec.ts
- runtime/auth-http.ts
See: https://github.com/blackbaud/skyux2/projects/9#card-10723204
> RC > Always provide `envId` regardless of permission scope

- lib/sky-pages-module-generator.js
- package.json
- runtime/config.ts
- skyuxconfig-schema.json
- test/sky-pages-module-generator.spec.js
Resolves: https://github.com/blackbaud/skyux2/issues/413
**Example skyuxconfig.json:**
```
{
"mode": "easy",
"compileMode": "aot",
"app": {
"styles": [
"@blackbaud/skyux/dist/css/sky.css",
"src/styles/custom.css"
]
}
}
```
> RC > Allow SPAs to bundle stylesheets that live outside of `src/app`

- runtime/pact.service.ts
While working on pact tests for my SPA, it was confusing/misleading to work with the SkyPactService class since it did not accurately represent the parameters and return types of it's functions.  Since this is just a wrapper class around pact-js, I've added the missing type info and method descriptions based on the official pact-js site.  This should help developers writing pact tests in their SPAs.
> Add better type info and documentation to SkyPactService.

- runtime/config-params.ts
- runtime/params.spec.ts
- runtime/params.ts
- skyuxconfig-schema.json
- skyuxconfig.json
Added option to exclude parameters from being added to requests sent by SkyAuthHttp
> Option to exclude params from request

- cli/build-public-library.js
- config/webpack/build-public-library.webpack.config.js
- package.json
- test/cli-build-public-library.spec.js
- test/config-webpack-build-public-library.spec.js
Resolves: https://github.com/blackbaud/skyux2/issues/1851
@Blackbaud-BobbyEarl I know we talked about avoiding `child_spawn`, but in this case I couldn't find a way around it. Library builds are failing because we're attempting to transpile and bundle in the same step, which causes some problems during AoT. To fix it, I'm transpiling _after_ the bundle has been created so that they don't interfere with one another.
To transpile the files, I need to use Angular's `ngc` (for the metadata), but they don't provide an NPM utility that can be used programmatically, from what I gathered. Also, nearly every tutorial I found recommended that we run `ngc` through the command-line. Another critical thing to note: Angular 6 provides a first-class way to generate libraries, so the changes in this pull …
> Libraries > Separated transpile and bundle actions

- cli/build-public-library.js
- test/cli-build-public-library.spec.js
`skyux build-public-library` is not working on Windows machines due to an incorrect usage of `cross-spawn`.
Also, I'm passing up the status code to fail the build if an error is encountered.
> Fixed library build failures on Windows machines

- runtime/pact.service.ts
Resolves: https://github.com/blackbaud/skyux2/issues/1852
The type will be added back in the new `@skyux-sdk/pact` library:
https://github.com/blackbaud/skyux-sdk-pact/blob/master/src/app/public/pact.service.ts#L45
> Reverted Pact interaction type for backwards compatibility

- lib/locale-assets-processor.js
- lib/sky-pages-assets-generator.js
- test/cli-utils-run-build.spec.js
- test/lib-locale-assets-processor.spec.js
- test/sky-pages-assets-generator.spec.js
Quick attempt at solving https://github.com/blackbaud/skyux2/issues/1773
> Changed logic to include the generated locales if no locale exists.

- cli/build-public-library.js
- cli/test.js
- config/webpack/test.webpack.config.js
- lib/locale-assets-processor.js
- test/cli-test.spec.js
- test/lib-locale-assets-processor.spec.js
- tsconfig.json
**This branch accomplishes the following:**
1. Allow SKY UX libraries to reference `.skypageslocales` resource files statically (see description below)
1. Related to above, we also need to generate resource files during `skyux test`.
1. Finally, I noticed that Karma is not catching browser errors. I added the appropriate hook for that.
**Why allow SKY UX libraries to reference resource files statically?**
SKY UX 2 libraries will need this (in particular) to avoid breaking changes with how they're currently handling resources. `SkyResources` is used internally by SKY UX components, but it is synchronous (see: https://github.com/blackbaud/skyux2/blob/master/src/modules/resources/resources.ts#L2).
However, the new libraries need to use Builder's `SkyAppResources` service, which is …
> Resolve locale resources

- cli/build.js
- test/cli-build.spec.js
SKY UX references Builder's `/cli/build.js` file during its visual tests. An older version of Builder used to return `stats` in the build's promise, but now it doesn't. This fails our visual tests.
Where SKY UX is referencing the build result:
https://github.com/blackbaud/skyux2/blob/master/skyux-spa-visual-tests/config/utils/start-visual.js#L192
> Re-added stats to the build promise result

- config/axe/axe.config.js
This should remain disabled until we can upgrade to using axe-core 3.1.1. The current version does not recognize certain attributes as appropriate for certain roles that we use together and will cause failures to this rule.
> Disable aria allowed attr

- appveyor.yml
- cli/build-public-library.js
- lib/plugin-file-processor.js
- test/cli-build-public-library.spec.js
- test/plugin-file-processor.spec.js
- This will allow plugins to affect the `skyux build-public-library` phase.
- Needed to accommodate the synchronous nature of `SkyResources` service.
This is being used, here: https://github.com/blackbaud/skyux-core/pull/31
> Added plugins hook to library bundler

- cli/build-public-library.js
- test/cli-build-public-library.spec.js
This will allow libraries to generate two modules in their NPM package: the "production" module (which is consumed by the SPA, and a "testing" module, which is used by the consuming SPA's unit tests.
```
import {
MyTestingModule
} from '@skyux/core/testing';
```
The library must include a "testing" directory in `./src/app/public` folder.
We need to include a separate file for the testing module so that its contents don't "pollute" the production module during a webpack build.
> Allow libraries to include an isolated "testing" module

- lib/sky-pages-module-generator.js
- package.json
- test/sky-pages-module-generator.spec.js
@Blackbaud-BobbyEarl I reverted some changes I made to the `sky-pages-module-generator`. I've tested this branch on skyux2 and a few internal SPAs.
This solves two problems:
1. Fixes the `No provider for SkyAuthHttp!` error.
2. I've updated `@skyux/i18n` to fix another problem that only occurred during unit tests. See: https://github.com/blackbaud/skyux-i18n/pull/11
> Update version of `@skyux/i18n`

- runtime/bootstrapper.ts
Recently the Stacktrace team have found issues in their spas/libs that could have been caught earlier by the tsc if `strict` was turned on, particularly `strictNullChecks`. If we try to turn on `strict` in our spas/libs we get errors that originate in skyux-builder because the builder is built in to the spas/libs. This PR aims to do the least amount of work possible to allow consumers to turn on `strict` if they choose.
It fixes the linting issues without changing any functionality or public / private api of skyux builder, mostly by:
- Changing the type with the issues into a union of `undefined`
- Using the [Non-null assertion operator](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator)
> Fix lint/tsc issues when the strict tsc flag is true

- config/protractor/protractor-dev.conf.js
Builder's internal e2e tests do not use the local source for `@blackbaud/skyux-builder`. This pull request fixes that.
> Use local source for e2e tests

- cli/generate.js
- index.js
- test/cli-generate.spec.js
- test/index.spec.js
https://github.com/blackbaud/skyux2/issues/1505
> Checking if files exists before writing in generate.  Allowing --force/-f to bypass.

- config/webpack/alias-builder.js
- package.json
- test/config-webpack-common.spec.js
Related: https://github.com/blackbaud/skyux-config/pull/16
SDK Builder, too: https://github.com/blackbaud/skyux-sdk-builder/pull/56
@Blackbaud-BobbyEarl We need to add this feature to Builder `1.x` because our libraries are still using it to maintain backwards compatibility with SKY UX 2.
> Add module aliases
