.travis.yml, README.md, cli/build.js, cli/serve.js, cli/version.js, cli/watch.js, config/karma/local.karma.conf.js, config/karma/shared.karma.conf.js, config/webpack/build.webpack.config.js, config/webpack/common.webpack.config.js, config/webpack/serve.webpack.config.js, jasmine.json, loader/sky-pages-asset/index.js, loader/sky-pages-module/index.js, package.json, test/cli-build.spec.js, test/cli-serve.spec.js, test/cli-version.spec.js, test/cli-watch.spec.js, test/config-karma-local.spec.js, test/config-karma-shared.spec.js, test/config-sky-pages.spec.js, test/config-webpack-build.spec.js, test/config-webpack-common.spec.js, test/config-webpack-serve.spec.js, test/config-webpack-test.spec.js, test/loader-asset.spec.js, test/loader-module.spec.js, test/sky-pages-out-skyux2.spec.js, utils/spec-bundle.js
https://github.com/blackbaud/sky-pages-cli/issues/11
https://github.com/blackbaud/sky-pages-cli/issues/10
=> Adding unit tests with 100% code coverage

tslint.json
@Blackbaud-JonathanBell can you confirm this is what you had to change?
=> Adjusted for npm v3 rules directory

config/webpack/common.webpack.config.js, test/config-webpack-common.spec.js
Fixes https://github.com/blackbaud/sky-pages-cli/issues/22
=> Allowing name to be overridden via sky-pages.json

plugin/save-metadata/index.js, test/config-webpack-build-aot.spec.js, test/config-webpack-build.spec.js
=> Using html-webpack-plugin chunk sorter to correctly sort assets + tests

config/webpack/common.webpack.config.js, skyuxconfig.json, src/main.ejs, test/index-ejs.spec.js
Locally, allows https://github.com/blackbaud/skyux-cli/issues/52
=> External assets

src/main.ejs
Just saw this when I created a new SkyUX app.
=> Fix close tag of sky-pages-app.

package.json
Fixes https://github.com/blackbaud/skyux-cli/issues/91
=> Added json-loader as dependency

config/webpack/alias-builder.js, config/webpack/common.webpack.config.js, config/webpack/test.webpack.config.js, runtime/testing/index.ts, runtime/testing/test-module.ts
Fixed up unit testing and added test module.
=> Testing module

.vscode/settings.json
https://code.visualstudio.com/updates/v1_10#_word-wrap-settings-redesign
=> Updated wordWrap settings

runtime/bootstrap-config.ts
Quick fix for https://github.com/blackbaud/skyux2/issues/431
Still working on having tests butI've spent way too long on it and they're still flaky https://github.com/blackbaud/skyux-builder/pull/89
=> Adding publicRoutes to class definition

CHANGELOG.md, package.json
=> Preparing for 1.0.0-beta.13 release

config/webpack/serve.webpack.config.js, test/config-webpack-serve.spec.js
Tackling this in more manageable chunks.  First part (currently most-needed) to solve https://github.com/blackbaud/skyux2/issues/415
=> Allowing envid + svcid to be passed through

lib/sky-pages-module-generator.js
Fixes [Issue #595](https://github.com/blackbaud/skyux2/issues/595)
=> Added SkyAppConfig to SkyAppTestModule's list of providers

lib/sky-pages-module-generator.js, lib/sky-pages-route-generator.js, test/sky-pages-module-generator.spec.js
Fixes https://github.com/blackbaud/skyux2/issues/620
=> Limiting what route properties are exposed in SkyAppConfig

loader/sky-processor/index.js, runtime/config.ts, test/loader-processor.spec.js
- Content would only get updated by the last plugin in the array
- Added tests
=> Fixed bug with content not being updated

config/karma/shared.karma.conf.js
- Fixes issue [#650](https://github.com/blackbaud/skyux2/issues/650)
=> Updated timeouts in Karma config

runtime/config.ts
Addresses [issue #622](https://github.com/blackbaud/skyux2/issues/622)
- @blackbaud-johnly: If this gets approved, we'll probably want to document this feature.
=> Added `appSettings` to SkyAppConfig

src/app/app.component.ts
- This PR would negate the need for #138 
The [auth-client PR #19](https://github.com/blackbaud/auth-client/pull/19/files) would still need to be approved.
=> Converted omnibar config to `any` type

cli/e2e.js
Addresses [issue #720](https://github.com/blackbaud/skyux2/issues/720)
=> Fixed host-utils.js

src/app/app.component.spec.ts
Fixes https://github.com/blackbaud/skyux2/issues/747
=> Added lots of tests for src/app

CHANGELOG.md, package.json
We can hold off on merging this if you have other stuff that needs to be merged into RC, @Blackbaud-BobbyEarl.
=> Release 1.0.0 rc.2

package.json, src/polyfills.ts
https://github.com/blackbaud/skyux2/issues/803
=> Add web-animation-polyfill to builder

runtime/config.ts
Without this, https://github.com/blackbaud/skyux-builder/pull/217 does not work.
=> Adding missing redirects to interface

CHANGELOG.md, package.json
@Blackbaud-PaulCrowder Feel free to edit the changelog, as needed.
=> Release 1.0.0 rc.9

package.json
=> Upgraded rxjs to 5.4.2

appveyor.yml
Running our test suite on Windows!
=> Adding appveyor.yml

src/app/app.component.spec.ts, src/app/app.component.ts
Fixes https://github.com/blackbaud/skyux2/issues/1239
=> Using original url case sensitivity

src/app/app.component.scss
updated the closed class on the widget to the new bb-help-closed class name
=> Update Help class name selector.

lib/assets-processor.js, test/lib-assets-processor.spec.js
https://github.com/blackbaud/skyux2/issues/889
=> Made the regular expression that finds asset paths lazy instead of greedy

.travis.yml
Fixes https://github.com/blackbaud/skyux2/issues/1284
=> Creating separate deploy stage

config/karma/shared.karma.conf.js, test/config-karma-shared.spec.js
Fixes https://github.com/blackbaud/skyux2/issues/1298
=> Correctly reading current command in shared Karma config

src/app/app.component.spec.ts, src/app/app.component.ts
Fixes https://github.com/blackbaud/skyux2/issues/1570
=> Preserve SPA params for local nav

runtime/params.spec.ts, runtime/params.ts
Fixes https://github.com/blackbaud/skyux2/issues/1597
=> Removing fragment from URL before handing to URLSearchParams

runtime/params.spec.ts, runtime/params.ts
Fixes https://github.com/blackbaud/skyux2/issues/1616 and https://github.com/blackbaud/skyux2/issues/1621
=> Fixed param encode/decode bugs

config/webpack/common.webpack.config.js, package.json
Related: https://github.com/blackbaud/skyux2/pull/1582
=> Added support for requiring JSON files

CHANGELOG.md, package.json
Worked with @blackbaud-johnly prior to submitting PR to incorporate his feedback.
=> Updated CHANGELOG.md and package.json for 1.13.0

package.json, runtime/bootstrapper.spec.ts, runtime/bootstrapper.ts, runtime/params.ts, src/app/app.component.spec.ts, src/app/app.component.ts
Allows a user to select an environment when none is provided or default to an environment if the user is only in one environment.
=> Environment picker

config/webpack/serve.webpack.config.js
Addresses: https://github.com/blackbaud/skyux2/issues/1325
=> Switched Webpack devtool for serve

package.json
Updates the Help library being used. 
https://github.com/blackbaud/skyux-lib-help/blob/master/CHANGELOG.md
=> updated package version for lib-help

config/webpack/build-public-library.webpack.config.js, test/cli-e2e.spec.js, test/config-webpack-build-public-library.spec.js
Addresses:
https://github.com/blackbaud/skyux2/issues/1654
https://github.com/blackbaud/skyux2/issues/1503
=> Handle dependencies in library bundle

src/app/app.component.spec.ts, src/app/app.component.ts
Related to https://github.com/blackbaud/skyux-builder-stache-search/pull/28
=> Navigate post message

cli/utils/stage-library-ts.js, test/cli-utils-stage-library-ts.spec.js
Partially addresses: https://github.com/blackbaud/skyux2/issues/1547, specifically: https://github.com/blackbaud/skyux2/issues/1547#issuecomment-393656744
=> Libraries > Allow multiline entry to `styleUrls`

skyuxconfig-schema.json, src/app/app.component.spec.ts, src/app/app.component.ts
See: https://github.com/blackbaud/skyux2/projects/9#card-10723192
=> RC > Removed legacy omnibar

cli/build-public-library.js, config/webpack/build-public-library.webpack.config.js, package.json, test/cli-build-public-library.spec.js, test/config-webpack-build-public-library.spec.js
Addresses: https://github.com/blackbaud/skyux2/issues/1745
=> Libraries > Use the same compiler as `skyux build`

CHANGELOG.md, package.json
Thanks for reviewing these ahead of time @blackbaud-johnly!
=> Updated CHANGELOG.md and package.json for 1.19.0

config/webpack/test.webpack.config.js, package.json
We will need to release this pull request, first: https://github.com/blackbaud/skyux-i18n/pull/18
=> Added json-loader to test config

config/webpack/serve.webpack.config.js
Related: https://github.com/angular/angular-cli/issues/11060
=> RC > Disable webpack dev server host check

.gitignore, package.json, tslint.json
I've been bit too many times by setting a test to `fit` or a spec to `fdescribe` and forgetting to change them back. This change now causes a tslint error when you forget to change them back.
=> Use tslint defocus
